import { atom } from "recoil";

export const genreState = atom({
  key: "genreState",
  default: {
    en: ["Comedy",
      "Fantasy",
      "Crime",
      "Drama",
      "Music",
      "Adventure",
      "History",
      "Thriller",
      "Animation",
      "Family",
      "Mystery",
      "Biography",
      "Action",
      "Film-Noir",
      "Romance",
      "Sci-Fi",
      "War",
      "Western",
      "Horror",
      "Musical",
      "Sport"],
    ar: [
      "كوميديا",
      "خيال",
      "جريمة",
      "دراما",
      "موسيقى",
      "مغامرة",
      "تاريخ",
      "اثارة",
      "انميشن",
      "عائلي",
      "غموض",
      "سيرة ذاتية",
      "اكشن",
      "فيلم نوار",
      "رومانسية",
      "خيال علمي",
      "حرب",
      "ويسترن",
      "رعب",
      "موسيقي",
      "رياضة"
    ]
  },
});
