import { NonAuthLayout } from "@/layouts";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NonAuthLayout>
        Home
      </NonAuthLayout>
    </>
  );
}
