import { ELanguage } from "@/enums";
import { useRayyanLanguage } from "@/hooks/use-rayyan-language";
import { NonAuthLayout } from "@/layouts";
import Head from "next/head";
import { useTranslation } from "react-i18next";

export default function Home() {
  const { changeLanguage } = useRayyanLanguage()
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>{t("pageTitle.home")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NonAuthLayout>
        Home
        <div onClick={() => changeLanguage(ELanguage.AR)}>العربية</div>
        <div onClick={() => changeLanguage(ELanguage.EN)}>EN</div>
      </NonAuthLayout>
    </>
  );
}
